### ISSUE TITLE
ability to include other files

### ISSUE THREAD

**Issue by z0mbie42** [astrocorp42/san#11]
> Also calling something that can't even include other files a "configuration format" is a joke.

**Comment by defnull** [comment]
This can, and should, be handled by the consuming application.

Opening additional files or traversing the file system in the parser would open the door for a whole class of security and other issues, and would increase the complexity of parsers significantly.

**Comment by z0mbie42** [comment]
I'm waiting the response from the original author about any serious data serialization format examples  doing it, but I think it will be discarded soon

**Comment by z0mbie42** [comment]
Closing because it's too complexe and not safe
