### ISSUE TITLE
Comment whitespace trimming necessary?

### ISSUE THREAD

**Issue by defnull** [astrocorp42/san#6]
In the comments section, it reads: "A whitespace immediately following the hash symbol will be trimmed."

I do not see a reason for this, and it creates an ambiguity: Scripts that edit (parse, modify, save) documents would have a hard time to preserve white space in comments, as the information, whether or not a leading space was trimmed, is lost during the parse step.

Is this rule necessary? If not, please consider removing this strange parsing rule. Programs that are interested in comments (e.g. for macro processing (yes, this will eventually happen)) can do the trimming themselves, if necessary.

**Comment by defnull** [comment]
Removing this rule would also cut the length of the comments section in half :)

**Comment by z0mbie42** [comment]
To be honest this one was quickly added and not really engineered.

I will investigate it, but I think you're right and it will certainly be removed?

**Comment by z0mbie42** [comment]
The first point is fixed in  6b34e90 I will investigate the second concerning multi line strings right now
